
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const UNSET_AUTHENTICATED = 'UNSET_AUTHENTICATED';
export const SET_PAGINATION = 'SET_PAGINATION';
export const RESET_PAGINATION = 'RESET_PAGINATION';
export const SET_EXPORT_CDATA = 'SET_EXPORT_CDATA';
export const RESET_EXPORT_CDATA = 'RESET_EXPORT_CDATA';