export default {
  ignoredRows: [0],
  ignoredRowSign: '>',
  columnDefaults: {
    cdata: {
      drawing: false,
      photo: false,
      idiogram: false,
    },
    material: {},
    reference: {},
    dna: {},
  },
  referenceColumns: {
    standardizedName: {
      genus: 11,
      species: 12,
      subsp: 13,
      var: 14,
      forma: 15,
      authors: 16,
    },
    literature: {
      displayType: 58,
      paperAuthor: 60,
      paperTitle: 61,
      seriesSource: 62,
      volume: 63,
      issue: 64,
      publisher: 65,
      editor: 66,
      year: 67,
      pages: 68,
      journalName: 69,
    },
    countedBy: 23,
    collectedBy: 48,
    identifiedBy: 50,
    checkedBy: 53,
    idWorld4: 40,
  },
  dataColumns: {
    cdata: {
      n: 17,
      dn: 18,
      x: 19,
      xRevised: 20,
      ploidyLevel: 21,
      ploidyLevelRevised: 22,
      countedDate: 24,
      karyotype: 25,
      numberOfAnalysedPlants: 26,
      slideNo: 27,
      depositedIn: 28,
      note: 29,
      drawing: 30,
      photo: 31,
      idiogram: 32,
    },
    dna: {
      method: 33,
      ploidy: 35,
      ploidyRevised: 36,
      plantsAnalysed: 37,
      numberAnalyses: 38,
      note: 39,
    },
    material: {
      country: 41,
      geographicalDistrict: 42,
      administrativeUnit: 43,
      closestVillageTown: 44,
      altitude: 45,
      exposition: 46,
      description: 47,
      collectedDate: 49,
      voucherSpecimenNo: 51,
      coordinatesLat: 54,
      coordinatesLon: 55,
      coordinatesGeorefLat: 56, // separated CSV columns but one DB column -> see facades/import.js/processMaterial()
      coordinatesGeorefLon: 57,
    },
    reference: {
      page: 59,
    },
    nameAsPublished: {
      genus: 6,
      species: 7,
      subsp: 8,
      var: 9,
      authors: 10,
    },
  },
};
